#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 20, 2019 09:47:54 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import stdnt_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    stdnt_support.set_Tk_var()
    top = Toplevel1 (root)
    stdnt_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    stdnt_support.set_Tk_var()
    top = Toplevel1 (w)
    stdnt_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x562+427+118")
        top.minsize(130, 10)
        top.maxsize(1380, 759)
        top.resizable(0, 0)
        top.title("student db")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.15, rely=0.036, relheight=0.436, relwidth=0.775)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.043, rely=0.041, height=21, width=38)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Name''')

        self.Label1_1 = tk.Label(self.Frame1)
        self.Label1_1.place(relx=0.043, rely=0.163, height=31, width=34)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Marks''')

        self.Label1_2 = tk.Label(self.Frame1)
        self.Label1_2.place(relx=0.043, rely=0.327, height=21, width=54)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Roll no.''')

        self.Label1_3 = tk.Label(self.Frame1)
        self.Label1_3.place(relx=0.043, rely=0.49, height=21, width=34)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Sex''')

        self.Label1_4 = tk.Label(self.Frame1)
        self.Label1_4.place(relx=0.043, rely=0.653, height=21, width=34)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Age''')

        self.Textname = tk.Text(self.Frame1)
        self.Textname.place(relx=0.28, rely=0.041, relheight=0.098
                , relwidth=0.525)
        self.Textname.configure(background="white")
        self.Textname.configure(font="-family {Segoe UI} -size 9")
        self.Textname.configure(foreground="black")
        self.Textname.configure(highlightbackground="#d9d9d9")
        self.Textname.configure(highlightcolor="black")
        self.Textname.configure(insertbackground="black")
        self.Textname.configure(selectbackground="#c4c4c4")
        self.Textname.configure(selectforeground="black")
        self.Textname.configure(wrap="word")

        self.Textmark = tk.Text(self.Frame1)
        self.Textmark.place(relx=0.28, rely=0.163, relheight=0.098
                , relwidth=0.525)
        self.Textmark.configure(background="white")
        self.Textmark.configure(font="-family {Segoe UI} -size 9")
        self.Textmark.configure(foreground="black")
        self.Textmark.configure(highlightbackground="#d9d9d9")
        self.Textmark.configure(highlightcolor="black")
        self.Textmark.configure(insertbackground="black")
        self.Textmark.configure(selectbackground="#c4c4c4")
        self.Textmark.configure(selectforeground="black")
        self.Textmark.configure(wrap="word")

        self.Textroll = tk.Text(self.Frame1)
        self.Textroll.place(relx=0.28, rely=0.286, relheight=0.098
                , relwidth=0.525)
        self.Textroll.configure(background="white")
        self.Textroll.configure(font="-family {Segoe UI} -size 9")
        self.Textroll.configure(foreground="black")
        self.Textroll.configure(highlightbackground="#d9d9d9")
        self.Textroll.configure(highlightcolor="black")
        self.Textroll.configure(insertbackground="black")
        self.Textroll.configure(selectbackground="#c4c4c4")
        self.Textroll.configure(selectforeground="black")
        self.Textroll.configure(wrap="word")

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.28, rely=0.449, relheight=0.143, relwidth=0.527)

        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")

        self.Radiobutton1 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1.place(relx=0.041, rely=0.286, relheight=0.429
                , relwidth=0.261)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''Male''')
        self.Radiobutton1.configure(variable=stdnt_support.selectedButton)

        self.Radiobutton1_7 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_7.place(relx=0.531, rely=0.286, relheight=0.429
                , relwidth=0.318)
        self.Radiobutton1_7.configure(activebackground="#ececec")
        self.Radiobutton1_7.configure(activeforeground="#000000")
        self.Radiobutton1_7.configure(background="#d9d9d9")
        self.Radiobutton1_7.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_7.configure(foreground="#000000")
        self.Radiobutton1_7.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_7.configure(highlightcolor="black")
        self.Radiobutton1_7.configure(justify='left')
        self.Radiobutton1_7.configure(text='''female''')
        self.Radiobutton1_7.configure(variable=stdnt_support.selectedButton)

        self.Spinbox1 = tk.Spinbox(self.Frame1, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.28, rely=0.653, relheight=0.078
                , relwidth=0.527)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(font="TkDefaultFont")
        self.Spinbox1.configure(foreground="black")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="black")
        self.Spinbox1.configure(insertbackground="black")
        self.Spinbox1.configure(selectbackground="#c4c4c4")
        self.Spinbox1.configure(selectforeground="black")
        self.Spinbox1.configure(textvariable=stdnt_support.spinbox)

        self.Button1show = tk.Button(top)
        self.Button1show.place(relx=0.2, rely=0.498, height=24, width=40)
        self.Button1show.configure(activebackground="#ececec")
        self.Button1show.configure(activeforeground="#000000")
        self.Button1show.configure(background="#d9d9d9")
        self.Button1show.configure(disabledforeground="#a3a3a3")
        self.Button1show.configure(foreground="#000000")
        self.Button1show.configure(highlightbackground="#d9d9d9")
        self.Button1show.configure(highlightcolor="black")
        self.Button1show.configure(pady="0")
        self.Button1show.configure(text='''Show''')

        self.Button1_add = tk.Button(top)
        self.Button1_add.place(relx=0.348, rely=0.511, height=24, width=47)
        self.Button1_add.configure(activebackground="#ececec")
        self.Button1_add.configure(activeforeground="#000000")
        self.Button1_add.configure(background="#d9d9d9")
        self.Button1_add.configure(disabledforeground="#a3a3a3")
        self.Button1_add.configure(foreground="#000000")
        self.Button1_add.configure(highlightbackground="#d9d9d9")
        self.Button1_add.configure(highlightcolor="black")
        self.Button1_add.configure(pady="0")
        self.Button1_add.configure(text='''Add''')

        self.Button1_modify = tk.Button(top)
        self.Button1_modify.place(relx=0.522, rely=0.507, height=24, width=47)
        self.Button1_modify.configure(activebackground="#ececec")
        self.Button1_modify.configure(activeforeground="#000000")
        self.Button1_modify.configure(background="#d9d9d9")
        self.Button1_modify.configure(disabledforeground="#a3a3a3")
        self.Button1_modify.configure(foreground="#000000")
        self.Button1_modify.configure(highlightbackground="#d9d9d9")
        self.Button1_modify.configure(highlightcolor="black")
        self.Button1_modify.configure(pady="0")
        self.Button1_modify.configure(text='''Modify''')

        self.Button1_del = tk.Button(top)
        self.Button1_del.place(relx=0.738, rely=0.516, height=24, width=47)
        self.Button1_del.configure(activebackground="#ececec")
        self.Button1_del.configure(activeforeground="#000000")
        self.Button1_del.configure(background="#d9d9d9")
        self.Button1_del.configure(disabledforeground="#a3a3a3")
        self.Button1_del.configure(foreground="#000000")
        self.Button1_del.configure(highlightbackground="#d9d9d9")
        self.Button1_del.configure(highlightcolor="black")
        self.Button1_del.configure(pady="0")
        self.Button1_del.configure(text='''Delete''')

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.183, rely=0.587, relheight=0.324
                , relwidth=0.74)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="-family {Courier New} -size 10")
        self.Listbox1.configure(foreground="#000000")

if __name__ == '__main__':
    vp_start_gui()





